### ISSUE TITLE
Cannot use nginx reverse proxy with any build

### ISSUE THREAD

**Issue by joeyhipolito** [cloudbees/jenkins-ci.org-docker#73]
It always returns 503 error, and cannot set upstream, for reverse proxy. Btw, I am using jwilder/nginx-proxy

**Comment by md5** [comment]
You need to set `-e VIRTUAL_PORT=8080` for `jwilder/nginx-proxy` to know which exposed port to proxy since `jenkins` exposes more than one port.

**Comment by Rocks360** [comment]
I get this error also. My docker-compose.yml looks like this: 

```
version: '2'
services:
  Jenkins:
    image: jenkins:latest
    container_name: jenkins
    ports:
      - "50000:50000"
    volumes:
      - /var/jenkins_home
    environment:
      - VIRTUAL_HOST=subdomain.mydomain.online, www.subdomain.mydomain.online
```

The reverse proxy already runs and proxied a container on port 80. I want now add jenkins also on port 80. So when I type in the Browser www.subdomain.mydomain.online nginx proxy to the jenkins container. I tried to build an own Dockerfile like this:

```
FROM jenkins
USER root
ENV JENKINS_OPTS --httpPort=80
EXPOSE 80
```
but don't get it solved. Have someone an Idea?
